### ISSUE TITLE
jasypt-spring-boot-starter-2.1.0 does not work with spring-boot-starter-1.5.8.RELEASE

### ISSUE THREAD

**Issue by dengjfeng** [ulisesbocchio/jasypt-spring-boot#113]

**Comment by dengjfeng** [comment]
I got this:

2018-12-10 10:53:26.931 |-DEBUG [main] com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor [64] -| Application Event Raised: ApplicationFailedEvent
2018-12-10 10:53:26.946 |-ERROR [main] org.springframework.boot.SpringApplication [771] -| Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lazyEncryptablePropertyFilter' defined in class path resource [com/ulisesbocchio/jasyptspringboot/configuration/EncryptablePropertyResolverConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ulisesbocchio.jasyptspringboot.EncryptablePropertyFilter]: Factory method 'encryptablePropertyFilter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/handler/IgnoreErrorsBindHandler
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at com.ulisesbocchio.jasyptspringboot.configuration.EnableEncryptablePropertiesBeanFactoryPostProcessor.postProcessBeanFactory(EnableEncryptablePropertiesBeanFactoryPostProcessor.java:52)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.cosmoplat.uuc.user.Application.main(Application.java:22)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ulisesbocchio.jasyptspringboot.EncryptablePropertyFilter]: Factory method 'encryptablePropertyFilter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/handler/IgnoreErrorsBindHandler
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/handler/IgnoreErrorsBindHandler
	at com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration.lambda$configProps$0(EncryptablePropertyResolverConfiguration.java:78)
	at com.ulisesbocchio.jasyptspringboot.util.Singleton.lambda$new$1(Singleton.java:20)
	at com.ulisesbocchio.jasyptspringboot.util.Singleton.get(Singleton.java:31)
	at com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration.encryptablePropertyFilter(EncryptablePropertyResolverConfiguration.java:101)
	at com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration$$EnhancerBySpringCGLIB$$59fe9b33.CGLIB$encryptablePropertyFilter$4(<generated>)
	at com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration$$EnhancerBySpringCGLIB$$59fe9b33$$FastClassBySpringCGLIB$$95965fec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.ulisesbocchio.jasyptspringboot.configuration.EncryptablePropertyResolverConfiguration$$EnhancerBySpringCGLIB$$59fe9b33.encryptablePropertyFilter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.handler.IgnoreErrorsBindHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 common frames omitted

**Comment by ulisesbocchio** [comment]
Yes, version 2 is not compatible with spring 1.5, use latest v1

**Comment by ulisesbocchio** [comment]
resolving this one
